spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8