spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/auction?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${DB_USER:auction_admin}
    password: ${DB_PASSWORD:aucpass}

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8