apiVersion: v1
kind: Service
metadata:
  name: {{ template "penny-auction-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "penny-auction-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ template "penny-auction-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
