fullnameOverride: penny-auction-service
replicaCount: 1

image:
  repository: javatechnologies/penny-auction-service
  tag: 0.3.0

service:
  type: NodePort
  port: 8080

health:
  path: /actuator/health

database:
  name: app_db
  user: app
  credentials: service-db-secret

resources:
  requests:
    memory: 521Mi
  limits:
    memory: 1024Mi

rsaPublicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCs4PEsAfzfPRrQc6sI6RSVrpdEKXhhwxAbRZlTZYdXNVUg7rcg34PnLuZD86IjIqf3vEXrmsR64HzN/jWPF1WeoFlq7j467ms1OJxRDaNSAovxcjJZSCuWcwu18V7X/zmANsH/khy0pw2cVPd6AnyaGpihUjAwc6RiuNKgOVCVWQIDAQAB"